### ISSUE TITLE
Add whitelist functionality

### ISSUE THREAD

**Issue by lkadalski** [Bisnode/opa-spring-security#10]
In current implementation we call open policy agent on every call. 
We lack whitelist functionality for endpoints like `/health` and so on.
Now `OPA-container` logs are shaded by every call from kubernetes. 
I'm not sure if it should be inside library or on user side?

**Comment by lukasz-kaminski** [comment]
For me it seems like a part of policy, which should be managed by OPA. With caching calling OPA repeatedly shouldn't be a problem.

**Comment by lkadalski** [comment]
I don't want to reach OPA for decision if I know that some endpoints I want expose for everyone.
I think this is a common functionality for some security projects?

**Comment by lukasz-kaminski** [comment]
Not necessarily, we should not make assumptions about the library's client's setup. Also this would break policy decoupling, you'd have two places now, where you allow/deny access.

**Comment by lukasz-kaminski** [comment]
Calling smart people: @anderseknert @irodzik

**Comment by anderseknert** [comment]
Calling OPA to decide on a static `/ping` endpoint every few seconds seems excessive. Other things you may want to be able to whitelist is static resources like images. So while it may be correct in an academic sense to always query OPA I'm leaning in favor of the pragmatic approach and would like to see the option of whitelisting some endpoints.

**Comment by anderseknert** [comment]
Do note though - nothing should be whitelisted by default.

**Comment by lukasz-kaminski** [comment]
I don't like breaking the main principle but I guess this feature would be requested sooner or later. It'll be implemented.

**Comment by anderseknert** [comment]
You won't need to break it - you will just need to allow for others to do so ;)

**Comment by radrys** [comment]
Feature merged to master
