### ISSUE TITLE
Unregister OAuth2 authorization web filter

### ISSUE THREAD

**Issue by lkadalski** [Bisnode/opa-spring-security#26]
As a developer I would have working OPA filter instead of OAuth Spring Security web filter.
When OAuth2 `org.springframework.security.oauth:spring-security-oauth` is present on class-path then the switch should be done.
This should be turn on by default, with option to turn off.

**Comment by anderseknert** [comment]
I'm not sure about the default - it's certainly possible that one would want to use the OAuth2 filter to check access tokens and scopes for example, while using the OPA filter for more fine grained permission checks. So I think we should be very careful about turning others configuration off by default.

**Comment by lukasz-kaminski** [comment]
Closing after some internal discussions.
